//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioGamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int IdHistorial { get; set; }
        public int Producto { get; set; }
        public System.DateTime Fecha_Movimiento { get; set; }
        public string Tipo_Movimiento { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public double Cantidad { get; set; }
        public double Cantidad_Anterior { get; set; }
        public double Cantidad_Actual { get; set; }
    }
}
