//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioGamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string NombreUsuario { get; set; }
        public string Llave { get; set; }
        public string Almacen { get; set; }
    }
}
